### ISSUE TITLE
Hide checked TODOs in embeded block refs

### ISSUE THREAD

**Issue by kerim** [mlanza/logseq-wide-eyed#2]
I have no idea if this is technically possible, but if it is that would be great, because I often use embedded block refs on my project pages and currently they are not hidden by the plugin.

**Comment by mlanza** [comment]
No worries. I have the perfect plugin:
https://github.com/mlanza/logseq-style-carousel
It's the one I use.  It does the same thing but an entirely different way.  It uses stylesheets and hides what's in the DOM.

I will caution you, install it locally using an unpacked plugin, per the Manual Installation.  Unfortunately, due to Logseq's internal security concerns it doesn't let a child iframe app (which is what my plugin is) read the parent document when installed via the marketplace.  This is not the case when you install it locally, which is how I have it installed on my machine.

The code is entirely open so you can inspect it and see there is nothing malicious about it.  Please give it a try and let me know if this gets you where you want to go.  I've been completely transparent about [why things are the way they are](https://github.com/mlanza/logseq-style-carousel/issues/1).

**Comment by kerim** [comment]
That works. Thanks!
