### ISSUE TITLE
Ability to choose particular pages where plugin works

### ISSUE THREAD

**Issue by kamilmodest** [mlanza/logseq-wide-eyed#6]
First of all, thank you for your plugin. It really useful and save my eyes from visual noise. ❤️

But, I use several pages with different scenarios so for some of pages is OK to be hidden when completed, but for some of them - NOT.

I see the option `target`, but it doesn't allow to choose particular page, just opt out all pages or all journal pages.

It would be really nice to have an ability to (at least) exclude some of pages by their name.
Because it's quite annoying to toggle plugin every time you switch the page.

**Comment by kamilmodest** [comment]
For example, what if here we can check if the page name contains in settings (as excluded page) and if so, then use empty array of blocks instead of real blocks?

https://github.com/mlanza/logseq-wide-eyed/blob/54725f53df21ab8df0efc5e6236c2462e7f0636f/index.js#L173

**Comment by mlanza** [comment]
You're welcome to the plugin but know I may retire it eventually.  I wrote a simpler, better implementation in [Style Carousel](https://github.com/mlanza/logseq-style-carousel), supplemented further by [Classy](https://github.com/mlanza/logseq-classy).  In fact, v2 of Wide Eyed plugin essentially has the internals of Style Carousel.  I just pushed it today.  The only change was to keep the icon you're familiar with.

Between these two plugins, assuming you can inspect and read the DOM and write CSS, because the DOM includes page titles, you can customize your stylesheet to achieve the page-specific customizations you want.  All Style Carousel does is makes it easy to add buttons which toggle things like showing/hiding completed todos.

**Comment by mlanza** [comment]
Please look to Style Carousel (it is the successor of Wide Eyed) and direct any issue you might have there.  Thank you.
